#!/bin/sh

DIRECTORY=`cat /etc/MUSICBRAINZ`
cd /tmp
rm -rf mb_temp
mkdir mb_temp
cd mb_temp
wget --recursive -nd ftp://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/latest-is-*
LATEST=`ls latest-is*`
echo $LATEST > $LATEST
LATEST=`sed s/latest-is-// $LATEST`
echo $LATEST

echo "getting the latest database exports from musicbrainz.org"
wget --recursive -nd ftp://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/$LATEST/
cd $DIRECTORY
carton exec ./admin/InitDb.pl -- --createdb --import /tmp/mb_temp/mbdump*.tar.bz2 


cd /tmp
rm -rf mb_temp

# copy the cron file into place for hourly replication packets
cp /root/musicbrainz_loadRepPackets /etc/cron.hourly

